//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SatOrbit.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_SatOrbitTYPE                129
#define IDD_SAT_NOTE                    130
#define IDD_TLE_IMP                     131
#define IDD_OPTION_BASE                 132
#define IDD_OPTION_TWOD                 133
#define IDR_ACTION                      134
#define IDD_SAT_INFO                    137
#define IDB_BITMAP                      138
#define IDD_SAT_3D                      139
#define IDR_MENU_3D                     140
#define IDR_SAT3DACCEL                  141
#define IDD_OPTION_THREED               142
#define IDI_ICON1                       145
#define IDC_TLE_IMP                     1006
#define IDC_SAT_LIST                    1006
#define IDC_B_IMPORT                    1007
#define IDC_SAT_DISPLAY                 1008
#define IDC_B_ADD                       1009
#define IDC_NOTE_TIME                   1009
#define IDC_TCS_STATE                   1009
#define IDC_BASE_STARTT                 1010
#define IDC_NOTE_DAY                    1010
#define IDC_BASE_ENDT                   1011
#define IDC_BASE_SPANT                  1012
#define IDC_RADIO1                      1013
#define IDC_RADIO_STATE                 1013
#define IDC_INFO_TIMESTATE              1013
#define IDC_RADIO2                      1014
#define IDC_TWOD_MAP                    1015
#define IDC_CHECK_GRID                  1016
#define IDC_CHECK_SAT                   1017
#define IDC_CHECK_SUN                   1018
#define IDC_CHECK_SATPOINT              1020
#define IDC_TWOD_MINANG                 1021
#define IDC_CHECK_COVER                 1022
#define IDC_TWOD_COVCOLOR               1023
#define IDC_RADIO3                      1024
#define IDC_RADIO_TIME                  1024
#define IDC_RADIO4                      1025
#define IDC_NOTE_SAT                    1028
#define IDC_LIST1                       1029
#define IDC_NOTE_SATINFO                1029
#define IDC_INFO_LIST                   1029
#define IDC_NOTE_LONG                   1030
#define IDC_EDIT2                       1031
#define IDC_NOTE_LAT                    1031
#define IDC_SITE_NAME                   1031
#define IDC_SITE_LON                    1032
#define IDC_EDIT1                       1033
#define IDC_INFO_TIME                   1033
#define IDC_REAL_LONG                   1033
#define IDC_BUTTON1                     1034
#define IDC_TIME_APPLY                  1034
#define IDC_BUTTON_UTC                  1034
#define IDC_CHECK1                      1035
#define IDC_INFO_QUERY                  1035
#define IDC_ORBIT3D_SHOW                1035
#define IDC_BUTTON2                     1036
#define IDC_QUERY_APPLY                 1036
#define IDC_INFO_SAT                    1037
#define IDC_SITE_LAT                    1038
#define IDC_SITE_ALT                    1039
#define IDC_TCS_AZ                      1040
#define IDC_TCS_EL                      1041
#define IDC_TCS_RA                      1042
#define IDC_STATE                       1043
#define IDC_BUTTON3                     1044
#define IDC_BUTTON_R                    1046
#define IDC_COVER3D_SHOW                1047
#define IDC_COMBO_MAP3D                 1048
#define IDC_COMBO_ORBITCOLOR            1049
#define IDC_COMBO_COVERCOLOR            1050
#define IDC_CHECK3                      1051
#define IDC_COORD3D_SHOW                1051
#define IDC_COMBO1                      1052
#define IDC_BASE_PLAYV                  1052
#define IDC_RADIO_                      1054
#define IDC_RADIO_POS                   1054
#define IDC_RADIO7                      1055
#define IDC_RADIO8                      1056
#define ID_TLE                          32771
#define ID_TLE_IM                       32772
#define ID_TLE_IMPORT                   32773
#define ID                              32774
#define ID_OPTION_BASE                  32775
#define ID_OPTION_TWO                   32776
#define ID_ACTION_PLAY                  32777
#define ID_ACTION_STOP                  32778
#define ID_Menu                         32779
#define ID_ACTION_RESET                 32780
#define ID_ACTION_                      32781
#define ID_ACTION_FORWARD               32782
#define ID_ACTION_BACK                  32783
#define ID_VIEW_ACTION                  32791
#define ID_ACTION_TIME                  32792
#define ID_FILE_DE                      32793
#define ID_INFO                         32794
#define IDC_INFO_3D                     32795
#define ID_32796                        32796
#define ID_ZOOM_OUT                     32798
#define ID_ZOOM_IN                      32800
#define ID_LOOK_LEFT                    32804
#define ID_LOOK_RIGHT                   32805
#define ID_LOOK_UP                      32806
#define ID_LOOK_DOWN                    32807
#define ID_OPTION_THREE                 32808
#define ID_LIGHT_SUN                    32809
#define ID_TLE_IN                       32810
#define ID_TLE_CLEAR                    32811
#define ID_BUTTON32816                  32816
#define ID_32817                        32817

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        146
#define _APS_NEXT_COMMAND_VALUE         32818
#define _APS_NEXT_CONTROL_VALUE         1057
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
